
import Head from 'next/head'
import { Stack, Button, Box } from '@mantine/core'


export default function Home() {
  return (
    <Stack sx={(theme) => ({ backgroundColor: theme.colors.dark[8] })}>
      <Head>
        <title>tuster</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Stack>
          <Box sx={(theme) => ({ backgroundColor: theme.colors.red[5] })}>
            <h1>
              Heading
            </h1>
            <Button>a button</Button>
          </Box>
          <Box sx={(theme) => ({ backgroundColor: theme.colors.blue[5] })}>
            Features
          </Box>
          <Box sx={(theme) => ({ backgroundColor: theme.colors.grape[5] })}>
            Testimonial
          </Box>
        </Stack>
      </main>
      <footer>
        <Box sx={(theme) => ({ backgroundColor: theme.colors.yellow[5] })}>
          footer
        </Box>
      </footer>
    </Stack>
  )
}
