
import Head from 'next/head'
import Navbar from './components/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />

        <div>
          <h1>
            Heading
          </h1>
          <button>a button</button>
        </div>

        <div>
          Features
        </div>

        <div>
          Testimonial
        </div>
      </main>

      <footer>
        <p>footer</p>
      </footer>
    </div>
  )
    }
